service:
  name: cottonbot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1 # Asia Pacific (Singapore)
  timeout: 100

custom:
  webpack:
    includeModules:
      forceInclude:
        - yarn
    packager: 'yarn'

functions:
  githubWebhookListener:
    handler: src/handlers/githubWebhook.githubWebhookListener
    events:
      - http:
          method: post
          path: githubWebhookListener
  restTrigger:
    handler: src/handlers/restTrigger.restTrigger
    events:
      - http:
          method: get
          path: restTrigger
