service:
  name: cottonbot

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1 # Asia Pacific (Singapore)
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

custom:
  webpack:
    includeModules:
      forceInclude:
        - yarn
    packager: 'yarn'

functions:
  githubWebhookListener:
    handler: src/handlers/githubWebhook.githubWebhookListener
    events:
      - http:
          method: post
          path: githubWebhookListener
  upgradeAllInstallations:
    handler: src/handlers/upgradeAllInstallations.upgradeAllInstallations
    environment:
      upgradeInstallationSnsArn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:upgradeInstallation"
    events:
      - http:
          method: get
          path: upgradeAllInstallations
  upgradeInstallation:
    handler: src/handlers/upgradeInstallation.upgradeInstallation
    timeout: 30
    events:
      - sns: upgradeInstallation
      - http:
          method: get
          path: upgradeInstallation/{instId}
          request:
            parameters:
              paths:
                instId: true
